### ISSUE TITLE
ArgumentException: The specified path is not of a legal form (empty).

### ISSUE THREAD

**Issue by ZanzyTHEbar** [gamedolphin/bevity#1]
Hello! 

Let me preface with, I hope this project takes off. A grand idea. 

I am setting up this repo rn, I have the unity version the same `2022.3.0f1`. 

I  have loaded the example project and ensured the the Bevity package is installed.
![image](https://github.com/gamedolphin/bevity/assets/45744329/9a7fbb38-46a0-4e74-b2f5-091da01f2da4)

I have tried all of the provided scenes, and an empty scene. 

Pressing play simply causes this error: 
```
ArgumentException: The specified path is not of a legal form (empty).
System.IO.Path.InsecureGetFullPath (System.String path) (at <6aa56e57ab504395b555cf3ed50fa53d>:0)
System.IO.Path.GetFullPath (System.String path) (at <6aa56e57ab504395b555cf3ed50fa53d>:0)
PlayMode.LaunchBevy () (at F:/Github/bevity/unity/sdk/Editor/PlayMode.cs:32)
PlayMode.OnPlayModeChange (UnityEditor.PlayModeStateChange state) (at F:/Github/bevity/unity/sdk/Editor/PlayMode.cs:19)
UnityEditor.EditorApplication.Internal_PlayModeStateChanged (UnityEditor.PlayModeStateChange state) (at <4911eca47f294e18a7b3306f02701303>:0)
```
I, of course, have rustup installed and my rust toolchain is up to date.

**Comment by ZanzyTHEbar** [comment]
To others who have this problem, the solution was removing the untitled scene ... of course it was.

I am now trying the provided example scenes again :)

**Comment by ZanzyTHEbar** [comment]
So far so good, working well now.

**Comment by ZanzyTHEbar** [comment]
So far so good, working well now.

**Comment by gamedolphin** [comment]
I'm glad it works for you! I'm happy someone other than me is looking at it!
